### ISSUE TITLE
iso8601-time: please add missing setup.hs file

### ISSUE THREAD

**Issue by LocutusOfBorg** [nh2/iso8601-time#9]
Hello, can you please add a simple Setup.hs file? it is really useful in Debian to bootstrap the build of the package

```diff
--- /dev/null
+++ haskell-iso8601-time-0.1.4/Setup.hs
@@ -0,0 +1,2 @@
+import Distribution.Simple
+main = defaultMain
```

**Comment by nh2** [comment]
Done!

**Comment by nh2** [comment]
Released on Hackage with https://hackage.haskell.org/package/iso8601-time-0.1.5

**Comment by LocutusOfBorg** [comment]
that was fast, thanks!
